function contentUi(x){
	return '<div class="outer-container" id="content1">'
+ '	<div class="container single-page">'
+ '	    <div class="row">'
+ '	        <div class="col-12 col-lg-9">'
+ '	            <div class="content-wrap">'
+ '	                <header class="entry-header">'
+ '	                    <div class="posted-date">'
+ '	                        January 30, 2018'
+ '	                    </div><!-- .posted-date -->'
+ '	'
+ '	                    <h2 class="entry-title">How to get dress on a hiking trip</h2>'
+ '	'
+ '	                    <div class="tags-links">'
+ '	                        <a href="#">#winter</a>'
+ '	                        <a href="#">#love</a>'
+ '	                        <a href="#">#snow</a>'
+ '	                        <a href="#">#january</a>'
+ '	                    </div><!-- .tags-links -->'
+ '	                </header><!-- .entry-header -->'
+ '	'
+ '	                <figure class="featured-image">'
+ '	                    <img src="'+x+'/resources/img/3.jpg" alt="">'
+ '	                </figure><!-- .featured-image -->'
+ '	'
+ '	                <div class="entry-content">'
+ '	                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel tortor facilisis, volutpat nulla placerat, tincidunt mi. Nullam vel orci dui. Suspendisse sit amet laoreet neque. Fusce sagittis suscipit sem a consequat. Proin nec interdum sem. Quisque in porttitor magna, a imperdiet est. </p>'
+ '	                </div><!-- .entry-content -->'
+ '	'
+ '	                <footer class="entry-footer flex flex-column flex-lg-row justify-content-between align-content-start align-lg-items-center">'
+ '	                    <ul class="post-share flex align-items-center order-3 order-lg-1">'
+ '	                        <label>Share</label>'
+ '	                        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>'
+ '	                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>'
+ '	                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>'
+ '	                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>'
+ '	                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>'
+ '	                    </ul><!-- .post-share -->'
+ '	'
+ '	                    <a class="read-more order-2" href="#">Read more</a>'
+ '	'
+ '	                    <div class="comments-count order-1 order-lg-3">'
+ '	                        <a href="#">2 Comments</a>'
+ '	                    </div><!-- .comments-count -->'
+ '	                </footer><!-- .entry-footer -->'
+ '	            </div><!-- .content-wrap -->'
+ '	'
+ '	            <div class="pagination">'
+ '	                <ul class="flex align-items-center">'
+ '	                    <li class="active"><a href="#">01.</a></li>'
+ '	                    <li><a href="#">02.</a></li>'
+ '	                    <li><a href="#">03.</a></li>'
+ '	                </ul>'
+ '	            </div>'
+ '	        </div><!-- .col -->'
+ '	'
+ '	        <div class="col-12 col-lg-3">'
+ '	            <div class="sidebar">'
+ '	                <div class="about-me">'
+ '	                    <h2>I’m Amelia Smith</h2>'
+ '	'
+ '	                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel tortor facilisis, volutpat nulla placerat, tincidunt mi. Nullam vel orci dui. Suspendisse sit amet laoreet neque. Fusce sagittis suscipit sem a consequat. Proin nec interdum sem. Quisque in porttitor magna.</p>'
+ '	                </div><!-- .about-me -->'
+ '	'
+ '	                <div class="recent-posts">'
+ '	                    <div class="recent-post-wrap">'
+ '	                        <figure>'
+ '	                            <img src="'+x+'/resources/img/thumb-1.jpg" alt="">'
+ '	                        </figure>'
+ '	'
+ '	                        <header class="entry-header">'
+ '	                            <div class="posted-date">'
+ '	                                January 30, 2018'
+ '	                            </div><!-- .entry-header -->'
+ '	'
+ '	                            <h3><a href="#">My fall in love story</a></h3>'
+ '	'
+ '	                        </header><!-- .entry-header -->'
+ '	                    </div><!-- .recent-post-wrap -->'
+ '	'
+ '	                </div><!-- .recent-posts -->'
+ '	'
+ '	            </div><!-- .sidebar -->'
+ '	        </div><!-- .col -->'
+ '	    </div><!-- .row -->'
+ '	</div><!-- .container -->'
+ '</div>';
}