function fluidUi(x){
	return '<div class="outer-container" id="fluid1">'
	+ '		<div class="container-fluid">'
	+ '		    <div class="row">'
	+ '		        <div class="col-12">'
	+ '		            <div class="swiper-container hero-slider">'
	+ '		                <div class="swiper-wrapper">'
	+ '		                    <div class="swiper-slide">'
	+ '		                        <div class="hero-content flex justify-content-center align-items-center flex-column">'
	+ '		                            <img src="'+x+'/resources/img/slider.jpg" alt="">'
	+ '		                        </div><!-- .hero-content -->'
	+ '		                    </div><!-- .swiper-slide -->'
	+ '			'
	+ '		                    <div class="swiper-slide">'
	+ '		                        <div class="hero-content flex justify-content-center align-items-center flex-column">'
	+ '		                            <img src="'+x+'/resources/img/slider.jpg" alt="">'
	+ '		                        </div><!-- .hero-content -->'
	+ '		                    </div><!-- .swiper-slide -->'
	+ '			'
	+ '		                    <div class="swiper-slide">'
	+ '		                        <div class="hero-content flex justify-content-center align-items-center flex-column">'
	+ '		                            <img src="'+x+'/resources/img/slider.jpg" alt="">'
	+ '		                        </div><!-- .hero-content -->'
	+ '		                    </div><!-- .swiper-slide -->'
	+ '		                </div><!-- .swiper-wrapper -->'
	+ '			'
	+ '		                <!-- Add Pagination -->'
	+ '		                <div class="swiper-pagination"></div>'
	+ '		'
	+ '		                <!-- Add Arrows -->'
	+ '		                <div class="swiper-button-next flex justify-content-center align-items-center">'
	+ '		                    <span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 27 44"><path d="M27,22L27,22L5,44l-2.1-2.1L22.8,22L2.9,2.1L5,0L27,22L27,22z"></path></svg></span>'
	+ '		                </div>'
	+ '		                <div class="swiper-button-prev flex justify-content-center align-items-center">'
	+ '		                    <span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 27 44"><path d="M0,22L22,0l2.1,2.1L4.2,22l19.9,19.9L22,44L0,22L0,22L0,22z"></path></svg></span>'
	+ '		                </div>'
	+ '		            </div><!-- .swiper-container -->'
	+ '		        </div><!-- .col -->'
	+ '		    </div><!-- .row -->'
	+ '		</div><!-- .hero-section -->'
	+ '	</div>';
}