function footerBarUi(){
	return '    <div class="footer-bar">'
		+ '    <div class="outer-container">'
		+ '    <div class="container-fluid">'
		+ '        <div class="row justify-content-between">'
		+ '            <div class="col-12 col-md-6">'
		+ '                <div class="footer-section">'
		+ '                	<h2>Wanna Start Work With Me? <a href="sweetmilky.dev@gmail.com" target="_blank"> sweetmilky@gmail.com</a></h2>'
		+ '                    <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#" target="_blank">Danah</a></p>'
		+ '                </div><!-- .footer-section -->'
		+ '            </div><!-- .col-xl-4 -->'
		+ ''
		+ '            <div class="col-12 col-md-6">'
		+ '                <div class="footer-social">'
		+ '                    <ul class="flex justify-content-center justify-content-md-end align-items-center">'
		+ '                        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>'
		+ '                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>'
		+ '                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>'
		+ '                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>'
		+ '                    </ul>'
		+ '                </div><!-- .footer-social -->'
		+ '            </div><!-- .col-xl-4 -->'
		+ '        </div><!-- .row -->'
		+ '    </div><!-- .container-fluid -->'
		+ '</div><!-- .outer-container -->'
		+ '</div><!-- .footer-bar -->';
}