function navUi(){
	return '<div class="container" id="nav1">'
        + '<div class="row">'
        + '    <div class="col-12">'
        + '        <div class="site-branding flex flex-column align-items-center">'
        + '            <h1 class="site-title"><a rel="home">Danah</a></h1>'
        + '            <p class="site-description">Personal Portfolio</p>'
        + '        </div><!-- .site-branding -->'
        + ''
        + '        <nav class="site-navigation">'
        + '            <div class="hamburger-menu d-lg-none">'
        + '                <span></span>'
        + '                <span></span>'
        + '                <span></span>'
        + '                <span></span>'
        + '            </div><!-- .hamburger-menu -->'
        + ''
        + '            <ul class="flex-lg flex-lg-row justify-content-lg-center align-content-lg-center">'
        + '                <li class="current-menu-item"><a href="index.html">Home</a></li>'
        + '                <li><a href="#">features</a></li>'
        + '                <li><a href="#">Portfolio</a></li>'
        + '                <li><a id="blogMenu" href="#">blog</a></li>'
        + '                <li><a href="#">about me</a></li>'
        + '                <li><a href="#">Contact</a></li>'
        + '            </ul>'
        + ''
        + '            <div class="header-bar-social d-md-none">'
        + '                <ul class="flex justify-content-center align-items-center">'
        + '                    <li><a href="#"><i class="fa fa-pinterest"></i></a></li>'
        + '                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>'
        + '                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>'
        + '                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>'
        + '                    <li><a id="boardMenu" href="#"><i class="fa fa-list-alt"></i></a></li>'
        + '                    <li id="menu1"><a id="loginMenu" href="#"><i class="fa fa-sign-in"></i></a></li>'
        + '                 <li id="menu2"><a id="addMenu" href="#"><i class="fa fa-user-plus"></i></a></li>'
        + '                </ul>'
        + '            </div><!-- .header-bar-social -->'
        + ''
        + '            <div class="header-bar-search d-md-none">'
        + '                <form>'
        + '                    <input type="search" placeholder="Search">'
        + '                </form>'
        + '            </div><!-- .header-bar-search -->'
        + '        </nav><!-- .site-navigation -->'
        + '    </div><!-- .col -->'
        + '</div><!-- .row -->'
        + '</div><!-- .container -->';
}