/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2018-08-31 03:09:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class nav_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-12\">\r\n");
      out.write("            <div class=\"site-branding flex flex-column align-items-center\">\r\n");
      out.write("                <h1 class=\"site-title\"><a rel=\"home\">Danah</a></h1>\r\n");
      out.write("                <p class=\"site-description\">Personal Portfolio</p>\r\n");
      out.write("            </div><!-- .site-branding -->\r\n");
      out.write(" \r\n");
      out.write("            <nav class=\"site-navigation\">\r\n");
      out.write("                <div class=\"hamburger-menu d-lg-none\">\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                </div><!-- .hamburger-menu -->\r\n");
      out.write(" \r\n");
      out.write("                <ul class=\"flex-lg flex-lg-row justify-content-lg-center align-content-lg-center\">\r\n");
      out.write("                    <li class=\"current-menu-item\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                    <li><a href=\"#\">features</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Portfolio</a></li>\r\n");
      out.write("                    <li><a href=\"#\">blog</a></li>\r\n");
      out.write("                    <li><a href=\"#\">about me</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write(" \r\n");
      out.write("                <div class=\"header-bar-social d-md-none\">\r\n");
      out.write("                    <ul class=\"flex justify-content-center align-items-center\">\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-pinterest\"></i></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>\r\n");
      out.write("                       <li class=\"dropdown\">\r\n");
      out.write("                        \t<a id=\"myMenu\" data-toggle=\"dropdown\" aria-haspopup=\"true\" role=\"button\" aria-expanded=\"false\">\r\n");
      out.write("                        \t\t<i class=\"fa fa-list-alt\"></i>\r\n");
      out.write("                        \t</a>\r\n");
      out.write("                        \t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                        \t\t<li role=\"presentation\"><a id=\"boardWriteMenu\" role=\"menuitem\" tabindex=\"-1\">게시글쓰기</a></li>\r\n");
      out.write("                        \t\t<li role=\"presentation\"><a id=\"boardListMenu\" role=\"menuitem\" tabindex=\"-1\">게시글목록</a></li>\r\n");
      out.write("                        \t</ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"dropdown\">\r\n");
      out.write("                        \t<a id=\"myMenu\" data-toggle=\"dropdown\" aria-haspopup=\"true\" role=\"button\" aria-expanded=\"false\">\r\n");
      out.write("                        \t\t<i class=\"fa fa-user\"></i>\r\n");
      out.write("                        \t</a>\r\n");
      out.write("                        \t<ul class=\"dropdown-menu\" role=\"menu\" aria-labelledby=\"drop1\">\r\n");
      out.write("                        \t\t<li role=\"presentation\"><a id=\"modifyMenu\" role=\"menuitem\" tabindex=\"-1\">정보수정</a></li>\r\n");
      out.write("                        \t\t<li role=\"presentation\"><a id=\"removeMenu\" role=\"menuitem\" tabindex=\"-1\">탈퇴</a></li>\r\n");
      out.write("                        \t</ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a id=\"logoutMenu\"><i class=\"fa fa-sign-out\"></i></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div><!-- .header-bar-social -->\r\n");
      out.write(" \r\n");
      out.write("                <div class=\"header-bar-search d-md-none\">\r\n");
      out.write("                    <form>\r\n");
      out.write("                        <input type=\"search\" placeholder=\"Search\">\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div><!-- .header-bar-search -->\r\n");
      out.write("            </nav><!-- .site-navigation -->\r\n");
      out.write("        </div><!-- .col -->\r\n");
      out.write("    </div><!-- .row -->\r\n");
      out.write("</div><!-- .container -->\r\n");
      out.write("<script>\r\n");
      out.write("$('.site-title').click (function(){\r\n");
      out.write("\tlocation.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/move/member/member/retrieve';\r\n");
      out.write("});\r\n");
      out.write("$('#boardWriteMenu').click (function(){\r\n");
      out.write("\talert('게시글쓰기');\r\n");
      out.write("\tlocation.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/move/member/member/register';\r\n");
      out.write("});\r\n");
      out.write("$('#boardListMenu').click (function(){\r\n");
      out.write("\talert('게시글목록');\r\n");
      out.write("\tlocation.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/move/member/member/listAll';\r\n");
      out.write("});\r\n");
      out.write("$('#modifyMenu').click (function(){\r\n");
      out.write("\tlocation.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/move/member/member/modify';\r\n");
      out.write("});\r\n");
      out.write("$('#removeMenu').click (function(){\r\n");
      out.write("\tlocation.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/move/member/member/remove';\r\n");
      out.write("});\r\n");
      out.write("$('#logoutMenu').click (function(){\r\n");
      out.write("\tlocation.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/logout';\r\n");
      out.write("});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
