function footerImgUi(x){
    return '<div class="container-fluid">'
        + '    <div class="row">'
        + '        <div class="footer-instagram flex flex-wrap flex-lg-nowrap">'
        + '            <figure>'
        + '                <a href="#"><img src="'+x+'/resources/img/a.jpg" alt=""></a>'
        + '            </figure>'
        + ''
        + '            <figure>'
        + '                <a href="#"><img src="'+x+'/resources/img/b.jpg" alt=""></a>'
        + '            </figure>'
        + ''
        + '            <figure>'
        + '                <a href="#"><img src="'+x+'/resources/img/c.jpg" alt=""></a>'
        + '            </figure>'
        + ''
        + '            <figure>'
        + '                    <a href="#"><img src="'+x+'/resources/img/d.jpg" alt=""></a>'
        + '            </figure>'
        + ''
        + '            <figure>'
        + '                <a href="#"><img src="'+x+'/resources/img/e.jpg" alt=""></a>'
        + '            </figure>'
        + ''
        + '            <figure>'
        + '                <a href="#"><img src="'+x+'/resources/img/f.jpg" alt=""></a>'
        + '            </figure>'
        + ''
        + '            <figure>'
        + '                <a href="#"><img src="'+x+'/resources/img/g.jpg" alt=""></a>'
        + '            </figure>'
        + '        </div>'
        + '    </div><!-- .row -->'
        + '</div><!-- .container -->';
}
