SELECT *
FROM MEMBER;

select count(*)
from member;

-- 삽입된 데이터 역순 정렬
SELECT T.*
FROM(SELECT ROWNUM SEQ, M.*
FROM MEMBER M
ORDER BY SEQ DESC)T
WHERE T.SEQ BETWEEN 1 AND 5;

SELECT T.* FROM(SELECT ROWNUM SEQ, M.* FROM MEMBER M ORDER BY SEQ DESC)T WHERE T.SEQ BETWEEN 1 AND 5;

SELECT MEM_ID , TEAM_ID , NAME , AGE , ROLL , PASS_WORD , SSN , GENDER , SUBJECT FROM MEMBER WHERE TEAM_ID IN  
%(SELECT TEAM_ID FROM RPROJECT_TEAM WHERE TEAM_NAME LIKE '저스티스')%;